commits:
  body:
    presence:
      enabled: false
  subject:
    prefix:
      enabled: false
      severity: warn
      includes:
        - Accept
        - Access
        - Add
        - Adjust
        - Aggregate
        - Allow
        - Append
        - Apply
        - Archive
        - Assert
        - Assign
        - Attempt
        - Authenticate
        - Authorize
        - Break
        - Build
        - Cache
        - Calculate
        - Call
        - Cancel
        - Capture
        - Change
        - Check
        - Clean
        - Clear
        - Close
        - Collect
        - Combine
        - Commit
        - Compare
        - Compute
        - Configure
        - Confirm
        - Connect
        - Construct
        - Control
        - Convert
        - Copy
        - Count
        - Create
        - Customize
        - Declare
        - Decode
        - Decorate
        - Define
        - Delegate
        - Delete
        - Deprecate
        - Derive
        - Describe
        - Detect
        - Determine
        - Disable
        - Display
        - Download
        - Drop
        - Dump
        - Emit
        - Empty
        - Enable
        - Encapsulate
        - Encode
        - End
        - Ensure
        - Enumerate
        - Establish
        - Evaluate
        - Examine
        - Exclude
        - Execute
        - Exit
        - Expand
        - Expect
        - Export
        - Extend
        - Extract
        - Feed
        - Fetch
        - Fill
        - Filter
        - Finalize
        - Find
        - Fire
        - Fix
        - Flag
        - Force
        - Format
        - Forward
        - Generate
        - Get
        - Give
        - Go
        - Group
        - Handle
        - Help
        - Hold
        - Identify
        - Implement
        - Import
        - Include
        - Indicate
        - Init
        - Initialize
        - Initiate
        - Input
        - Insert
        - Instantiate
        - Intercept
        - Invoke
        - Iterate
        - Join
        - Keep
        - Launch
        - List
        - Listen
        - Load
        - Log
        - Look
        - Make
        - Manage
        - Manipulate
        - Map
        - Mark
        - Match
        - Merge
        - Mock
        - Modify
        - Monitor
        - Move
        - Normalize
        - Note
        - Obtain
        - Open
        - Output
        - Override
        - Overwrite
        - Package
        - Pad
        - Parse
        - Partial
        - Pass
        - Perform
        - Persist
        - Pick
        - Plot
        - Poll
        - Populate
        - Post
        - Prepare
        - Print
        - Process
        - Produce
        - Provide
        - Publish
        - Pull
        - Put
        - Query
        - Raise
        - Read
        - Record
        - Refactor
        - Refer
        - Refresh
        - Register
        - Reload
        - Remove
        - Rename
        - Render
        - Replace
        - Reply
        - Report
        - Represent
        - Request
        - Require
        - Reset
        - Resolve
        - Respond
        - Retrieve
        - Return
        - Revert
        - Roll
        - Rollback
        - Round
        - Run
        - Sample
        - Save
        - Scan
        - Search
        - Select
        - Send
        - Separate
        - Serialize
        - Serve
        - Set
        - Show
        - Simplify
        - Simulate
        - Source
        - Specify
        - Split
        - Start
        - Step
        - Stop
        - Store
        - Strip
        - Submit
        - Subscribe
        - Sum
        - Surface
        - Swap
        - Sync
        - Synchronize
        - Take
        - Tear
        - Test
        - Time
        - Transform
        - Translate
        - Transmit
        - Trim
        - Truncate
        - Try
        - Turn
        - Tweak
        - Update
        - Upload
        - Use
        - Validate
        - Verify
        - View
        - Wait
        - Walk
        - Wrap
        - Write
        - Yield
