commits:
  subject:
    prefix:
      enabled: true
      severity: warn
      includes:
        - "([A-Z]+-[0-9]+ )?Add"
        - "([A-Z]+-[0-9]+ )?Update"
        - "([A-Z]+-[0-9]+ )?Fix"
        - "([A-Z]+-[0-9]+ )?Remove"
        - "([A-Z]+-[0-9]+ )?Refactor"
